name: 'First Flow'

on: workflow_dispatch

jobs:
  simple:
    name: 'First Flow'
    runs-on:
      - ubuntu-22.04
    steps:
      - name: "Simple Step"
        run: 
          "echo 'Hello World'"
